name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 使用更新版本的 checkout
      - name: Checkout repository
        uses: actions/checkout@v4  # 确保是 v4 版本
        
      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: Tartaglia770
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # 如果使用 peaceiris/actions-gh-pages，考虑更新到 v4
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4  # 更新到 v4 版本
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
